# Generated by Django 3.2.4 on 2021-06-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('twentyfour_hour_vol', models.BigIntegerField(blank=True, null=True)),
                ('twentyfour_hour_change', models.BigIntegerField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printer.prices'),
        ),
    ]
