# Generated by Django 3.2.4 on 2021-06-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_auto_20210612_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='prices',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printer.prices'),
        ),
    ]
