# Generated by Django 3.2.4 on 2021-06-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_coin_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='prices',
        ),
        migrations.AddField(
            model_name='coin',
            name='prices_eur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_eur', to='printer.prices'),
        ),
        migrations.AddField(
            model_name='coin',
            name='prices_usd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_usd', to='printer.prices'),
        ),
    ]
