# Generated by Django 3.2.4 on 2021-06-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20210613_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='currentprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='prices_eur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_eur', to='printer.prices'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='prices_usd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_usd', to='printer.prices'),
        ),
    ]
